# Documentation for webpack for WordPress Boilerplate..
#
# Author: Ahmad Awais, Maedah Batool, Ashar Irfan.
# License: Copyright held by WPCouple.
#
# MKDOCS http://www.mkdocs.org/
# mkdocs-material http://squidfunk.github.io/mkdocs-material/

site_name: webpack for WordPress
site_description: 'Documentation for webpack for WordPress.'
site_author: 'Ahmad Awais', 'Maedah Batool'
#site_url: 'https://ahmadawais.github.io/vrdoc'

# Repository
repo_name: 'GitHub'
#repo_url: 'https://github.com/ahmadawais/vrdoc'

# Copyright
copyright: 'Copyright &copy; 2017 WPCouple'

theme:
  name: 'material'
  palette:
    primary: 'light blue'
    accent: 'indigo'
  font:
      text: 'Ubuntu'
      code: 'Ubuntu Mono'




